site_name: CPP Optimizations diary

site_description: Tip and tricks to optimize your C++ code.
site_author: Davide Faconti

copyright: 'Copyright &copy; 2020 Davide Faconti'

theme:
  name: 'material'
  language: en
  logo: 'img/cpp.png'
  palette:
    primary: blue grey
    accent: purple
  font:
    text: Ubuntu
    code: Roboto Mono
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  
repo_name: 'CPP_Optimizations_Diary'
repo_url: 'https://github.com/facontidavide/CPP_Optimizations_Diary'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/facontidavide

markdown_extensions:
  - admonition
  - codehilite

google_analytics:
  - UA-134735656-2
  - auto
  
nav:
  - Home: index.md

  - Reference and move semantic:
    - Use references: prefer_references.md

  - Vectors are your best friend:
    - Use reserve: reserve.md
    - Avoid std::list : no_lists.md
    - You may not need std::map : dont_need_map.md
    - Small vector optimization: small_vectors.md

  - "It's just a string...":
    - Strings are vectors: strings_are_vectors.md
    - Small string optimization: small_strings.md
    - String concatenation: strings_concatenation.md
        
  - Don't compute it twice:
    - Iterating over a 2D matrix: 2d_matrix_iteration.md
    
  - Case studies:
    - Faster and simpler PCL filter:  pcl_filter.md

  - About me: about.md
    
